version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "8000:8000"  # Map port 8000 from the container to port 8000 on the host